const fs = require('fs');

const countriesJSON = [
  {
    'Alpha-2 code': 'AF',
    'Alpha-3 code': 'AFG',
    Numeric: 4,
    'English short name': 'Afghanistan',
    'French short name': "Afghanistan (l')",
    'Avarni name (Original)': 'afghanistan',
    'Avarni name (Updated)': 'Afghanistan',
    'Alternate Spellings': 'Islamic Republic of Afghanistan',
  },
  {
    'Alpha-2 code': 'AL',
    'Alpha-3 code': 'ALB',
    Numeric: 8,
    'English short name': 'Albania',
    'French short name': "Albanie (l')",
    'Avarni name (Original)': 'albania',
    'Avarni name (Updated)': 'Albania',
    'Alternate Spellings': 'Republic of Albania',
  },
  {
    'Alpha-2 code': 'DZ',
    'Alpha-3 code': 'DZA',
    Numeric: 12,
    'English short name': 'Algeria',
    'French short name': "Algérie (l')",
    'Avarni name (Original)': 'algeria',
    'Avarni name (Updated)': 'Algeria',
    'Alternate Spellings': "People's Democratic Republic of Algeria",
  },
  {
    'Alpha-2 code': 'AS',
    'Alpha-3 code': 'ASM',
    Numeric: 16,
    'English short name': 'American Samoa',
    'French short name': 'Samoa américaines (les)',
    'Avarni name (Original)': '',
    'Avarni name (Updated)': 'American Samoa',
    'Alternate Spellings': 'Territory of American Samoa',
  },
  {
    'Alpha-2 code': 'AD',
    'Alpha-3 code': 'AND',
    Numeric: 20,
    'English short name': 'Andorra',
    'French short name': "Andorre (l')",
    'Avarni name (Original)': 'andorra',
    'Avarni name (Updated)': 'Andorra',
    'Alternate Spellings': 'Principality of Andorra',
  },
  {
    'Alpha-2 code': 'AO',
    'Alpha-3 code': 'AGO',
    Numeric: 24,
    'English short name': 'Angola',
    'French short name': "Angola (l')",
    'Avarni name (Original)': 'angola',
    'Avarni name (Updated)': 'Angola',
    'Alternate Spellings': 'Republic of Angola',
  },
  {
    'Alpha-2 code': 'AI',
    'Alpha-3 code': 'AIA',
    Numeric: 660,
    'English short name': 'Anguilla',
    'French short name': 'Anguilla',
    'Avarni name (Original)': '',
    'Avarni name (Updated)': 'Anguilla',
    'Alternate Spellings': '',
  },
  {
    'Alpha-2 code': 'AQ',
    'Alpha-3 code': 'ATA',
    Numeric: 10,
    'English short name': 'Antarctica',
    'French short name': "Antarctique (l')",
    'Avarni name (Original)': '',
    'Avarni name (Updated)': 'Antarctica',
    'Alternate Spellings': '',
  },
  {
    'Alpha-2 code': 'AG',
    'Alpha-3 code': 'ATG',
    Numeric: 28,
    'English short name': 'Antigua and Barbuda',
    'French short name': 'Antigua-et-Barbuda',
    'Avarni name (Original)': 'antigua',
    'Avarni name (Updated)': 'Antigua',
    'Alternate Spellings': 'Antigua and Barbuda, Antigua & Barbuda',
  },
  {
    'Alpha-2 code': 'AR',
    'Alpha-3 code': 'ARG',
    Numeric: 32,
    'English short name': 'Argentina',
    'French short name': "Argentine (l')",
    'Avarni name (Original)': 'argentina',
    'Avarni name (Updated)': 'Argentina',
    'Alternate Spellings': 'Argentine Republic',
  },
  {
    'Alpha-2 code': 'AM',
    'Alpha-3 code': 'ARM',
    Numeric: 51,
    'English short name': 'Armenia',
    'French short name': "Arménie (l')",
    'Avarni name (Original)': 'armenia',
    'Avarni name (Updated)': 'Armenia',
    'Alternate Spellings': 'Republic of Armenia',
  },
  {
    'Alpha-2 code': 'AW',
    'Alpha-3 code': 'ABW',
    Numeric: 533,
    'English short name': 'Aruba',
    'French short name': 'Aruba',
    'Avarni name (Original)': 'aruba',
    'Avarni name (Updated)': 'Aruba',
    'Alternate Spellings': '',
  },
  {
    'Alpha-2 code': 'AU',
    'Alpha-3 code': 'AUS',
    Numeric: 36,
    'English short name': 'Australia',
    'French short name': "Australie (l')",
    'Avarni name (Original)': 'australia',
    'Avarni name (Updated)': 'Australia',
    'Alternate Spellings': 'Commonwealth of Australia',
  },
  {
    'Alpha-2 code': 'AT',
    'Alpha-3 code': 'AUT',
    Numeric: 40,
    'English short name': 'Austria',
    'French short name': "Autriche (l')",
    'Avarni name (Original)': 'austria',
    'Avarni name (Updated)': 'Austria',
    'Alternate Spellings': 'Republic of Austria',
  },
  {
    'Alpha-2 code': 'AZ',
    'Alpha-3 code': 'AZE',
    Numeric: 31,
    'English short name': 'Azerbaijan',
    'French short name': "Azerbaïdjan (l')",
    'Avarni name (Original)': 'azerbaijan',
    'Avarni name (Updated)': 'Azerbaijan',
    'Alternate Spellings': 'Republic of Azerbaijan',
  },
  {
    'Alpha-2 code': 'BS',
    'Alpha-3 code': 'BHS',
    Numeric: 44,
    'English short name': 'Bahamas (the)',
    'French short name': 'Bahamas (les)',
    'Avarni name (Original)': 'bahamas',
    'Avarni name (Updated)': 'Bahamas',
    'Alternate Spellings': 'Commonwealth of The Bahamas, The Bahamas',
  },
  {
    'Alpha-2 code': 'BH',
    'Alpha-3 code': 'BHR',
    Numeric: 48,
    'English short name': 'Bahrain',
    'French short name': 'Bahreïn',
    'Avarni name (Original)': 'bahrain',
    'Avarni name (Updated)': 'Bahrain',
    'Alternate Spellings': 'Kingdom of Bahrain',
  },
  {
    'Alpha-2 code': 'BD',
    'Alpha-3 code': 'BGD',
    Numeric: 50,
    'English short name': 'Bangladesh',
    'French short name': 'Bangladesh (le)',
    'Avarni name (Original)': 'bangladesh',
    'Avarni name (Updated)': 'Bangladesh',
    'Alternate Spellings': "People's Republic of Bangladesh",
  },
  {
    'Alpha-2 code': 'BB',
    'Alpha-3 code': 'BRB',
    Numeric: 52,
    'English short name': 'Barbados',
    'French short name': 'Barbade (la)',
    'Avarni name (Original)': 'barbados',
    'Avarni name (Updated)': 'Barbados',
    'Alternate Spellings': '',
  },
  {
    'Alpha-2 code': 'BY',
    'Alpha-3 code': 'BLR',
    Numeric: 112,
    'English short name': 'Belarus',
    'French short name': 'Bélarus (le)',
    'Avarni name (Original)': 'belarus',
    'Avarni name (Updated)': 'Belarus',
    'Alternate Spellings': 'Republic of Belarus, White Russia',
  },
  {
    'Alpha-2 code': 'BE',
    'Alpha-3 code': 'BEL',
    Numeric: 56,
    'English short name': 'Belgium',
    'French short name': 'Belgique (la)',
    'Avarni name (Original)': 'belgium',
    'Avarni name (Updated)': 'Belgium',
    'Alternate Spellings': 'Kingdom of Belgium',
  },
  {
    'Alpha-2 code': 'BZ',
    'Alpha-3 code': 'BLZ',
    Numeric: 84,
    'English short name': 'Belize',
    'French short name': 'Belize (le)',
    'Avarni name (Original)': 'belize',
    'Avarni name (Updated)': 'Belize',
    'Alternate Spellings': '',
  },
  {
    'Alpha-2 code': 'BJ',
    'Alpha-3 code': 'BEN',
    Numeric: 204,
    'English short name': 'Benin',
    'French short name': 'Bénin (le)',
    'Avarni name (Original)': 'benin',
    'Avarni name (Updated)': 'Benin',
    'Alternate Spellings': 'Republic of Benin',
  },
  {
    'Alpha-2 code': 'BM',
    'Alpha-3 code': 'BMU',
    Numeric: 60,
    'English short name': 'Bermuda',
    'French short name': 'Bermudes (les)',
    'Avarni name (Original)': 'bermuda',
    'Avarni name (Updated)': 'Bermuda',
    'Alternate Spellings': '',
  },
  {
    'Alpha-2 code': 'BT',
    'Alpha-3 code': 'BTN',
    Numeric: 64,
    'English short name': 'Bhutan',
    'French short name': 'Bhoutan (le)',
    'Avarni name (Original)': 'bhutan',
    'Avarni name (Updated)': 'Bhutan',
    'Alternate Spellings': 'Kingdom of Bhutan',
  },
  {
    'Alpha-2 code': 'BO',
    'Alpha-3 code': 'BOL',
    Numeric: 68,
    'English short name': 'Bolivia (Plurinational State of)',
    'French short name': 'Bolivie (État plurinational de)',
    'Avarni name (Original)': 'bolivia',
    'Avarni name (Updated)': 'Bolivia',
    'Alternate Spellings': 'Plurinational State of Bolivia',
  },
  {
    'Alpha-2 code': 'BQ',
    'Alpha-3 code': 'BES',
    Numeric: 535,
    'English short name': 'Bonaire, Sint Eustatius and Saba',
    'French short name': 'Bonaire, Saint-Eustache et Saba',
    'Avarni name (Original)': '',
    'Avarni name (Updated)': 'Bonaire Sint Eustatius And Saba',
    'Alternate Spellings':
      'Caribbean Netherlands, Bonaire, Bonaire Sint Eustatius & Saba',
  },
  {
    'Alpha-2 code': 'BA',
    'Alpha-3 code': 'BIH',
    Numeric: 70,
    'English short name': 'Bosnia and Herzegovina',
    'French short name': 'Bosnie-Herzégovine (la)',
    'Avarni name (Original)': 'bosnia and herzegovina',
    'Avarni name (Updated)': 'Bosnia And Herzegovina',
    'Alternate Spellings': 'bosnia & herzegovina, Bosnia',
  },
  {
    'Alpha-2 code': 'BW',
    'Alpha-3 code': 'BWA',
    Numeric: 72,
    'English short name': 'Botswana',
    'French short name': 'Botswana (le)',
    'Avarni name (Original)': 'botswana',
    'Avarni name (Updated)': 'Botswana',
    'Alternate Spellings': 'Republic of Botswana',
  },
  {
    'Alpha-2 code': 'BV',
    'Alpha-3 code': 'BVT',
    Numeric: 74,
    'English short name': 'Bouvet Island',
    'French short name': "Bouvet (l'Île)",
    'Avarni name (Original)': '',
    'Avarni name (Updated)': 'Bouvet Island',
    'Alternate Spellings': '',
  },
  {
    'Alpha-2 code': 'BR',
    'Alpha-3 code': 'BRA',
    Numeric: 76,
    'English short name': 'Brazil',
    'French short name': 'Brésil (le)',
    'Avarni name (Original)': 'brazil',
    'Avarni name (Updated)': 'Brazil',
    'Alternate Spellings':
      'Federative Republic of Brazil, Brasil, Federative Republic of Brasil',
  },
  {
    'Alpha-2 code': 'IO',
    'Alpha-3 code': 'IOT',
    Numeric: 86,
    'English short name': 'British Indian Ocean Territory (the)',
    'French short name': "Indien (le Territoire britannique de l'océan)",
    'Avarni name (Original)': '',
    'Avarni name (Updated)': 'British Indian Ocean Territory',
    'Alternate Spellings': 'The British Indian Ocean Territory',
  },
  {
    'Alpha-2 code': 'BN',
    'Alpha-3 code': 'BRN',
    Numeric: 96,
    'English short name': 'Brunei Darussalam',
    'French short name': 'Brunéi Darussalam (le)',
    'Avarni name (Original)': 'brunei',
    'Avarni name (Updated)': 'Brunei',
    'Alternate Spellings': 'Nation of Brunei, Brunei Darussalam',
  },
  {
    'Alpha-2 code': 'BG',
    'Alpha-3 code': 'BGR',
    Numeric: 100,
    'English short name': 'Bulgaria',
    'French short name': 'Bulgarie (la)',
    'Avarni name (Original)': 'bulgaria',
    'Avarni name (Updated)': 'Bulgaria',
    'Alternate Spellings': 'Republic of Bulgaria',
  },
  {
    'Alpha-2 code': 'BF',
    'Alpha-3 code': 'BFA',
    Numeric: 854,
    'English short name': 'Burkina Faso',
    'French short name': 'Burkina Faso (le)',
    'Avarni name (Original)': 'burkina',
    'Avarni name (Updated)': 'Burkina',
    'Alternate Spellings': 'Burkina Faso',
  },
  {
    'Alpha-2 code': 'BI',
    'Alpha-3 code': 'BDI',
    Numeric: 108,
    'English short name': 'Burundi',
    'French short name': 'Burundi (le)',
    'Avarni name (Original)': 'burundi',
    'Avarni name (Updated)': 'Burundi',
    'Alternate Spellings': 'Republic of Burundi',
  },
  {
    'Alpha-2 code': 'CV',
    'Alpha-3 code': 'CPV',
    Numeric: 132,
    'English short name': 'Cabo Verde',
    'French short name': 'Cabo Verde',
    'Avarni name (Original)': 'cape verde',
    'Avarni name (Updated)': 'Cape Verde',
    'Alternate Spellings': 'Republic of Cabo Verde, Cabo Verde',
  },
  {
    'Alpha-2 code': 'KH',
    'Alpha-3 code': 'KHM',
    Numeric: 116,
    'English short name': 'Cambodia',
    'French short name': 'Cambodge (le)',
    'Avarni name (Original)': 'cambodia',
    'Avarni name (Updated)': 'Cambodia',
    'Alternate Spellings': 'Kingdom of Cambodia',
  },
  {
    'Alpha-2 code': 'CM',
    'Alpha-3 code': 'CMR',
    Numeric: 120,
    'English short name': 'Cameroon',
    'French short name': 'Cameroun (le)',
    'Avarni name (Original)': 'cameroon',
    'Avarni name (Updated)': 'Cameroon',
    'Alternate Spellings': 'Republic of Cameroon',
  },
  {
    'Alpha-2 code': 'CA',
    'Alpha-3 code': 'CAN',
    Numeric: 124,
    'English short name': 'Canada',
    'French short name': 'Canada (le)',
    'Avarni name (Original)': 'canada',
    'Avarni name (Updated)': 'Canada',
    'Alternate Spellings': 'Dominion of Canada',
  },
  {
    'Alpha-2 code': 'KY',
    'Alpha-3 code': 'CYM',
    Numeric: 136,
    'English short name': 'Cayman Islands (the)',
    'French short name': 'Caïmans (les Îles)',
    'Avarni name (Original)': 'cayman islands',
    'Avarni name (Updated)': 'Cayman Islands',
    'Alternate Spellings': 'The Cayman Islands',
  },
  {
    'Alpha-2 code': 'CF',
    'Alpha-3 code': 'CAF',
    Numeric: 140,
    'English short name': 'Central African Republic (the)',
    'French short name': 'République centrafricaine (la)',
    'Avarni name (Original)': 'central african republic',
    'Avarni name (Updated)': 'Central African Republic',
    'Alternate Spellings': 'The Central African Republic',
  },
  {
    'Alpha-2 code': 'TD',
    'Alpha-3 code': 'TCD',
    Numeric: 148,
    'English short name': 'Chad',
    'French short name': 'Tchad (le)',
    'Avarni name (Original)': 'chad',
    'Avarni name (Updated)': 'Chad',
    'Alternate Spellings': 'Republic of Chad',
  },
  {
    'Alpha-2 code': 'CL',
    'Alpha-3 code': 'CHL',
    Numeric: 152,
    'English short name': 'Chile',
    'French short name': 'Chili (le)',
    'Avarni name (Original)': 'chile',
    'Avarni name (Updated)': 'Chile',
    'Alternate Spellings': 'Republic of Chile',
  },
  {
    'Alpha-2 code': 'CN',
    'Alpha-3 code': 'CHN',
    Numeric: 156,
    'English short name': 'China',
    'French short name': 'Chine (la)',
    'Avarni name (Original)': 'china',
    'Avarni name (Updated)': 'China',
    'Alternate Spellings': "People's Republic of China",
  },
  {
    'Alpha-2 code': 'CX',
    'Alpha-3 code': 'CXR',
    Numeric: 162,
    'English short name': 'Christmas Island',
    'French short name': "Christmas (l'Île)",
    'Avarni name (Original)': '',
    'Avarni name (Updated)': 'Christmas Island',
    'Alternate Spellings': '',
  },
  {
    'Alpha-2 code': 'CC',
    'Alpha-3 code': 'CCK',
    Numeric: 166,
    'English short name': 'Cocos (Keeling) Islands (the)',
    'French short name': 'Cocos (les Îles)/ Keeling (les Îles)',
    'Avarni name (Original)': '',
    'Avarni name (Updated)': 'Cocos Islands',
    'Alternate Spellings':
      'Cocos Islands, Cocos Keeling Islands, The Cocos Keeling Islands, Territory of Cocos (Keeling) Islands, Cocos (Keeling) Islands',
  },
  {
    'Alpha-2 code': 'CO',
    'Alpha-3 code': 'COL',
    Numeric: 170,
    'English short name': 'Colombia',
    'French short name': 'Colombie (la)',
    'Avarni name (Original)': 'colombia',
    'Avarni name (Updated)': 'Colombia',
    'Alternate Spellings': 'Republic of Colombia',
  },
  {
    'Alpha-2 code': 'KM',
    'Alpha-3 code': 'COM',
    Numeric: 174,
    'English short name': 'Comoros (the)',
    'French short name': 'Comores (les)',
    'Avarni name (Original)': 'comoros',
    'Avarni name (Updated)': 'Comoros',
    'Alternate Spellings': 'Union of the Comoros, The Comoros',
  },
  {
    'Alpha-2 code': 'CD',
    'Alpha-3 code': 'COD',
    Numeric: 180,
    'English short name': 'Congo (the Democratic Republic of the)',
    'French short name': 'Congo (la République démocratique du)',
    'Avarni name (Original)': 'democratic republic congo',
    'Avarni name (Updated)': 'Democratic Republic Congo',
    'Alternate Spellings':
      'The Democratic Republic of the Congo, Democratic Republic of the Congo',
  },
  {
    'Alpha-2 code': 'CG',
    'Alpha-3 code': 'COG',
    Numeric: 178,
    'English short name': 'Congo (the)',
    'French short name': 'Congo (le)',
    'Avarni name (Original)': 'Congo',
    'Avarni name (Updated)': 'Congo',
    'Alternate Spellings': 'Republic of the Congo, The Congo',
  },
  {
    'Alpha-2 code': 'CK',
    'Alpha-3 code': 'COK',
    Numeric: 184,
    'English short name': 'Cook Islands (the)',
    'French short name': 'Cook (les Îles)',
    'Avarni name (Original)': '',
    'Avarni name (Updated)': 'Cook Islands',
    'Alternate Spellings': 'The Cook Islands',
  },
  {
    'Alpha-2 code': 'CR',
    'Alpha-3 code': 'CRI',
    Numeric: 188,
    'English short name': 'Costa Rica',
    'French short name': 'Costa Rica (le)',
    'Avarni name (Original)': 'costa rica',
    'Avarni name (Updated)': 'Costa Rica',
    'Alternate Spellings': 'Republic of Costa Rica',
  },
  {
    'Alpha-2 code': 'HR',
    'Alpha-3 code': 'HRV',
    Numeric: 191,
    'English short name': 'Croatia',
    'French short name': 'Croatie (la)',
    'Avarni name (Original)': 'croatia',
    'Avarni name (Updated)': 'Croatia',
    'Alternate Spellings': 'Republic of Croatia',
  },
  {
    'Alpha-2 code': 'CU',
    'Alpha-3 code': 'CUB',
    Numeric: 192,
    'English short name': 'Cuba',
    'French short name': 'Cuba',
    'Avarni name (Original)': 'cuba',
    'Avarni name (Updated)': 'Cuba',
    'Alternate Spellings': 'Republic of Cuba',
  },
  {
    'Alpha-2 code': 'CW',
    'Alpha-3 code': 'CUW',
    Numeric: 531,
    'English short name': 'Curaçao',
    'French short name': 'Curaçao',
    'Avarni name (Original)': '',
    'Avarni name (Updated)': 'Curaçao',
    'Alternate Spellings': 'Curacao',
  },
  {
    'Alpha-2 code': 'CY',
    'Alpha-3 code': 'CYP',
    Numeric: 196,
    'English short name': 'Cyprus',
    'French short name': 'Chypre',
    'Avarni name (Original)': 'cyprus',
    'Avarni name (Updated)': 'Cyprus',
    'Alternate Spellings': 'Republic of Cyprus',
  },
  {
    'Alpha-2 code': 'CZ',
    'Alpha-3 code': 'CZE',
    Numeric: 203,
    'English short name': 'Czechia',
    'French short name': 'Tchéquie (la)',
    'Avarni name (Original)': 'czech republic',
    'Avarni name (Updated)': 'Czech Republic',
    'Alternate Spellings': 'Czechia, Czech Republic, The Czech Republic',
  },
  {
    'Alpha-2 code': 'CI',
    'Alpha-3 code': 'CIV',
    Numeric: 384,
    'English short name': "Côte d'Ivoire",
    'French short name': "Côte d'Ivoire (la)",
    'Avarni name (Original)': 'ivory coast',
    'Avarni name (Updated)': 'Ivory Coast',
    'Alternate Spellings':
      "Republic of Côte d'Ivoire, Côte d'Ivoire, Cote d'Ivoire",
  },
  {
    'Alpha-2 code': 'DK',
    'Alpha-3 code': 'DNK',
    Numeric: 208,
    'English short name': 'Denmark',
    'French short name': 'Danemark (le)',
    'Avarni name (Original)': 'denmark',
    'Avarni name (Updated)': 'Denmark',
    'Alternate Spellings': 'Kingdom of Denmark',
  },
  {
    'Alpha-2 code': 'DJ',
    'Alpha-3 code': 'DJI',
    Numeric: 262,
    'English short name': 'Djibouti',
    'French short name': 'Djibouti',
    'Avarni name (Original)': 'djibouti',
    'Avarni name (Updated)': 'Djibouti',
    'Alternate Spellings': 'Republic of Djibouti',
  },
  {
    'Alpha-2 code': 'DM',
    'Alpha-3 code': 'DMA',
    Numeric: 212,
    'English short name': 'Dominica',
    'French short name': 'Dominique (la)',
    'Avarni name (Original)': 'dominica',
    'Avarni name (Updated)': 'Dominica',
    'Alternate Spellings': 'Commonwealth of Dominica',
  },
  {
    'Alpha-2 code': 'DO',
    'Alpha-3 code': 'DOM',
    Numeric: 214,
    'English short name': 'Dominican Republic (the)',
    'French short name': 'dominicaine (la République)',
    'Avarni name (Original)': 'dominican republic',
    'Avarni name (Updated)': 'Dominican Republic',
    'Alternate Spellings': 'The Dominican Republic',
  },
  {
    'Alpha-2 code': 'EC',
    'Alpha-3 code': 'ECU',
    Numeric: 218,
    'English short name': 'Ecuador',
    'French short name': "Équateur (l')",
    'Avarni name (Original)': 'ecuador',
    'Avarni name (Updated)': 'Ecuador',
    'Alternate Spellings': 'Republic of Ecuador',
  },
  {
    'Alpha-2 code': 'EG',
    'Alpha-3 code': 'EGY',
    Numeric: 818,
    'English short name': 'Egypt',
    'French short name': "Égypte (l')",
    'Avarni name (Original)': 'egypt',
    'Avarni name (Updated)': 'Egypt',
    'Alternate Spellings': 'Arab Republic of Egypt',
  },
  {
    'Alpha-2 code': 'SV',
    'Alpha-3 code': 'SLV',
    Numeric: 222,
    'English short name': 'El Salvador',
    'French short name': 'El Salvador',
    'Avarni name (Original)': 'el salvador',
    'Avarni name (Updated)': 'El Salvador',
    'Alternate Spellings': 'Republic of El Salvador',
  },
  {
    'Alpha-2 code': 'GQ',
    'Alpha-3 code': 'GNQ',
    Numeric: 226,
    'English short name': 'Equatorial Guinea',
    'French short name': 'Guinée équatoriale (la)',
    'Avarni name (Original)': 'equatorial guinea',
    'Avarni name (Updated)': 'Equatorial Guinea',
    'Alternate Spellings': 'Republic of Equatorial Guinea',
  },
  {
    'Alpha-2 code': 'ER',
    'Alpha-3 code': 'ERI',
    Numeric: 232,
    'English short name': 'Eritrea',
    'French short name': "Érythrée (l')",
    'Avarni name (Original)': 'eritrea',
    'Avarni name (Updated)': 'Eritrea',
    'Alternate Spellings': 'State of Eritrea',
  },
  {
    'Alpha-2 code': 'EE',
    'Alpha-3 code': 'EST',
    Numeric: 233,
    'English short name': 'Estonia',
    'French short name': "Estonie (l')",
    'Avarni name (Original)': 'estonia',
    'Avarni name (Updated)': 'Estonia',
    'Alternate Spellings': 'Republic of Estonia',
  },
  {
    'Alpha-2 code': 'SZ',
    'Alpha-3 code': 'SWZ',
    Numeric: 748,
    'English short name': 'Eswatini',
    'French short name': "Eswatini (l')",
    'Avarni name (Original)': 'swaziland',
    'Avarni name (Updated)': 'Swaziland',
    'Alternate Spellings': 'Kingdom of Eswatini, Eswatini',
  },
  {
    'Alpha-2 code': 'ET',
    'Alpha-3 code': 'ETH',
    Numeric: 231,
    'English short name': 'Ethiopia',
    'French short name': "Éthiopie (l')",
    'Avarni name (Original)': 'ethiopia',
    'Avarni name (Updated)': 'Ethiopia',
    'Alternate Spellings': 'Federal Democratic Republic of Ethiopia',
  },
  {
    'Alpha-2 code': 'FK',
    'Alpha-3 code': 'FLK',
    Numeric: 238,
    'English short name': 'Falkland Islands (the)',
    'French short name': 'Falkland (les Îles)/Malouines (les Îles)',
    'Avarni name (Original)': '',
    'Avarni name (Updated)': 'Falkland Islands',
    'Alternate Spellings':
      'Falkland Islands (Malvinas), The Falkland Islands, Malvinas, Islas Malvinas',
  },
  {
    'Alpha-2 code': 'FO',
    'Alpha-3 code': 'FRO',
    Numeric: 234,
    'English short name': 'Faroe Islands (the)',
    'French short name': 'Féroé (les Îles)',
    'Avarni name (Original)': 'faroe islands',
    'Avarni name (Updated)': 'Faroe Islands',
    'Alternate Spellings': 'The Faroe Islands',
  },
  {
    'Alpha-2 code': 'FJ',
    'Alpha-3 code': 'FJI',
    Numeric: 242,
    'English short name': 'Fiji',
    'French short name': 'Fidji (les)',
    'Avarni name (Original)': 'fiji',
    'Avarni name (Updated)': 'Fiji',
    'Alternate Spellings': 'Republic of Fiji',
  },
  {
    'Alpha-2 code': 'FI',
    'Alpha-3 code': 'FIN',
    Numeric: 246,
    'English short name': 'Finland',
    'French short name': 'Finlande (la)',
    'Avarni name (Original)': 'finland',
    'Avarni name (Updated)': 'Finland',
    'Alternate Spellings': 'Republic of Finland',
  },
  {
    'Alpha-2 code': 'FR',
    'Alpha-3 code': 'FRA',
    Numeric: 250,
    'English short name': 'France',
    'French short name': 'France (la)',
    'Avarni name (Original)': 'france',
    'Avarni name (Updated)': 'France',
    'Alternate Spellings': 'French Republic',
  },
  {
    'Alpha-2 code': 'GF',
    'Alpha-3 code': 'GUF',
    Numeric: 254,
    'English short name': 'French Guiana',
    'French short name': 'Guyane française (la )',
    'Avarni name (Original)': '',
    'Avarni name (Updated)': 'French Guiana',
    'Alternate Spellings': '',
  },
  {
    'Alpha-2 code': 'PF',
    'Alpha-3 code': 'PYF',
    Numeric: 258,
    'English short name': 'French Polynesia',
    'French short name': 'Polynésie française (la)',
    'Avarni name (Original)': 'french polynesia',
    'Avarni name (Updated)': 'French Polynesia',
    'Alternate Spellings': '',
  },
  {
    'Alpha-2 code': 'TF',
    'Alpha-3 code': 'ATF',
    Numeric: 260,
    'English short name': 'French Southern Territories (the)',
    'French short name': 'Terres australes françaises (les)',
    'Avarni name (Original)': '',
    'Avarni name (Updated)': 'The French Southern Territories',
    'Alternate Spellings': 'The French Southern Territories',
  },
  {
    'Alpha-2 code': 'GA',
    'Alpha-3 code': 'GAB',
    Numeric: 266,
    'English short name': 'Gabon',
    'French short name': 'Gabon (le)',
    'Avarni name (Original)': 'gabon',
    'Avarni name (Updated)': 'Gabon',
    'Alternate Spellings': 'Gabonese Republic',
  },
  {
    'Alpha-2 code': 'GM',
    'Alpha-3 code': 'GMB',
    Numeric: 270,
    'English short name': 'Gambia (the)',
    'French short name': 'Gambie (la)',
    'Avarni name (Original)': 'gambia',
    'Avarni name (Updated)': 'Gambia',
    'Alternate Spellings': 'Republic of The Gambia, The Gambia',
  },
  {
    'Alpha-2 code': 'GE',
    'Alpha-3 code': 'GEO',
    Numeric: 268,
    'English short name': 'Georgia',
    'French short name': 'Géorgie (la)',
    'Avarni name (Original)': 'georgia',
    'Avarni name (Updated)': 'Georgia',
    'Alternate Spellings': '',
  },
  {
    'Alpha-2 code': 'DE',
    'Alpha-3 code': 'DEU',
    Numeric: 276,
    'English short name': 'Germany',
    'French short name': "Allemagne (l')",
    'Avarni name (Original)': 'germany',
    'Avarni name (Updated)': 'Germany',
    'Alternate Spellings': 'Federal Republic of Germany',
  },
  {
    'Alpha-2 code': 'GH',
    'Alpha-3 code': 'GHA',
    Numeric: 288,
    'English short name': 'Ghana',
    'French short name': 'Ghana (le)',
    'Avarni name (Original)': 'ghana',
    'Avarni name (Updated)': 'Ghana',
    'Alternate Spellings': 'Republic of Ghana',
  },
  {
    'Alpha-2 code': 'GI',
    'Alpha-3 code': 'GIB',
    Numeric: 292,
    'English short name': 'Gibraltar',
    'French short name': 'Gibraltar',
    'Avarni name (Original)': 'gibraltar',
    'Avarni name (Updated)': 'Gibraltar',
    'Alternate Spellings': '',
  },
  {
    'Alpha-2 code': 'GR',
    'Alpha-3 code': 'GRC',
    Numeric: 300,
    'English short name': 'Greece',
    'French short name': 'Grèce (la)',
    'Avarni name (Original)': 'greece',
    'Avarni name (Updated)': 'Greece',
    'Alternate Spellings': 'Hellenic Republic',
  },
  {
    'Alpha-2 code': 'GL',
    'Alpha-3 code': 'GRL',
    Numeric: 304,
    'English short name': 'Greenland',
    'French short name': 'Groenland (le)',
    'Avarni name (Original)': 'greenland',
    'Avarni name (Updated)': 'Greenland',
    'Alternate Spellings': '',
  },
  {
    'Alpha-2 code': 'GD',
    'Alpha-3 code': 'GRD',
    Numeric: 308,
    'English short name': 'Grenada',
    'French short name': 'Grenade (la)',
    'Avarni name (Original)': 'grenada',
    'Avarni name (Updated)': 'Grenada',
    'Alternate Spellings': '',
  },
  {
    'Alpha-2 code': 'GP',
    'Alpha-3 code': 'GLP',
    Numeric: 312,
    'English short name': 'Guadeloupe',
    'French short name': 'Guadeloupe (la)',
    'Avarni name (Original)': '',
    'Avarni name (Updated)': 'Guadeloupe',
    'Alternate Spellings': '',
  },
  {
    'Alpha-2 code': 'GU',
    'Alpha-3 code': 'GUM',
    Numeric: 316,
    'English short name': 'Guam',
    'French short name': 'Guam',
    'Avarni name (Original)': '',
    'Avarni name (Updated)': 'Guam',
    'Alternate Spellings': 'Territory of Guam',
  },
  {
    'Alpha-2 code': 'GT',
    'Alpha-3 code': 'GTM',
    Numeric: 320,
    'English short name': 'Guatemala',
    'French short name': 'Guatemala (le)',
    'Avarni name (Original)': 'guatemala',
    'Avarni name (Updated)': 'Guatemala',
    'Alternate Spellings': 'Republic of Guatemala',
  },
  {
    'Alpha-2 code': 'GG',
    'Alpha-3 code': 'GGY',
    Numeric: 831,
    'English short name': 'Guernsey',
    'French short name': 'Guernesey',
    'Avarni name (Original)': '',
    'Avarni name (Updated)': 'Guernsey',
    'Alternate Spellings': '',
  },
  {
    'Alpha-2 code': 'GN',
    'Alpha-3 code': 'GIN',
    Numeric: 324,
    'English short name': 'Guinea',
    'French short name': 'Guinée (la)',
    'Avarni name (Original)': 'guinea',
    'Avarni name (Updated)': 'Guinea',
    'Alternate Spellings': 'Republic of Guinea',
  },
  {
    'Alpha-2 code': 'GW',
    'Alpha-3 code': 'GNB',
    Numeric: 624,
    'English short name': 'Guinea-Bissau',
    'French short name': 'Guinée-Bissau (la)',
    'Avarni name (Original)': 'guinea-bissau',
    'Avarni name (Updated)': 'Guinea-Bissau',
    'Alternate Spellings': 'Republic of Guinea-Bissau',
  },
  {
    'Alpha-2 code': 'GY',
    'Alpha-3 code': 'GUY',
    Numeric: 328,
    'English short name': 'Guyana',
    'French short name': 'Guyana (le)',
    'Avarni name (Original)': 'guyana',
    'Avarni name (Updated)': 'Guyana',
    'Alternate Spellings': 'Co-operative Republic of Guyana',
  },
  {
    'Alpha-2 code': 'HT',
    'Alpha-3 code': 'HTI',
    Numeric: 332,
    'English short name': 'Haiti',
    'French short name': 'Haïti',
    'Avarni name (Original)': 'haiti',
    'Avarni name (Updated)': 'Haiti',
    'Alternate Spellings': 'Republic of Haiti',
  },
  {
    'Alpha-2 code': 'HM',
    'Alpha-3 code': 'HMD',
    Numeric: 334,
    'English short name': 'Heard Island and McDonald Islands',
    'French short name': "Heard-et-Îles MacDonald (l'Île)",
    'Avarni name (Original)': '',
    'Avarni name (Updated)': 'Heard Island And Mcdonald Islands',
    'Alternate Spellings':
      'Heard and McDonald Islands, HIMI, Territory of Heard Island and McDonald Islands',
  },
  {
    'Alpha-2 code': 'VA',
    'Alpha-3 code': 'VAT',
    Numeric: 336,
    'English short name': 'Holy See (the)',
    'French short name': 'Saint-Siège (le)',
    'Avarni name (Original)': '',
    'Avarni name (Updated)': 'The Holy See',
    'Alternate Spellings':
      'Vatican City, Vatican, Holy Vatican, See of Rome, Apostolic See, Pontifical See, Holy See',
  },
  {
    'Alpha-2 code': 'HN',
    'Alpha-3 code': 'HND',
    Numeric: 340,
    'English short name': 'Honduras',
    'French short name': 'Honduras (le)',
    'Avarni name (Original)': 'honduras',
    'Avarni name (Updated)': 'Honduras',
    'Alternate Spellings': 'Republic of Honduras',
  },
  {
    'Alpha-2 code': 'HK',
    'Alpha-3 code': 'HKG',
    Numeric: 344,
    'English short name': 'Hong Kong',
    'French short name': 'Hong Kong',
    'Avarni name (Original)': 'hong kong',
    'Avarni name (Updated)': 'Hong Kong',
    'Alternate Spellings': 'Hongkong, HK',
  },
  {
    'Alpha-2 code': 'HU',
    'Alpha-3 code': 'HUN',
    Numeric: 348,
    'English short name': 'Hungary',
    'French short name': 'Hongrie (la)',
    'Avarni name (Original)': 'hungary',
    'Avarni name (Updated)': 'Hungary',
    'Alternate Spellings': 'Republic of Hungary, Magyarország',
  },
  {
    'Alpha-2 code': 'IS',
    'Alpha-3 code': 'ISL',
    Numeric: 352,
    'English short name': 'Iceland',
    'French short name': "Islande (l')",
    'Avarni name (Original)': 'iceland',
    'Avarni name (Updated)': 'Iceland',
    'Alternate Spellings': 'Republic of Iceland, Ísland',
  },
  {
    'Alpha-2 code': 'IN',
    'Alpha-3 code': 'IND',
    Numeric: 356,
    'English short name': 'India',
    'French short name': "Inde (l')",
    'Avarni name (Original)': 'india',
    'Avarni name (Updated)': 'India',
    'Alternate Spellings': 'Republic of India, Bharat',
  },
  {
    'Alpha-2 code': 'ID',
    'Alpha-3 code': 'IDN',
    Numeric: 360,
    'English short name': 'Indonesia',
    'French short name': "Indonésie (l')",
    'Avarni name (Original)': 'indonesia',
    'Avarni name (Updated)': 'Indonesia',
    'Alternate Spellings':
      'Republic of Indonesia, Indonésia, Indonesian Archipelago',
  },
  {
    'Alpha-2 code': 'IR',
    'Alpha-3 code': 'IRN',
    Numeric: 364,
    'English short name': 'Iran (Islamic Republic of)',
    'French short name': "Iran (République Islamique d')",
    'Avarni name (Original)': 'iran',
    'Avarni name (Updated)': 'Iran',
    'Alternate Spellings': 'Islamic Republic of Iran, Persia',
  },
  {
    'Alpha-2 code': 'IQ',
    'Alpha-3 code': 'IRQ',
    Numeric: 368,
    'English short name': 'Iraq',
    'French short name': "Iraq (l')",
    'Avarni name (Original)': 'iraq',
    'Avarni name (Updated)': 'Iraq',
    'Alternate Spellings': 'Republic of Iraq',
  },
  {
    'Alpha-2 code': 'IE',
    'Alpha-3 code': 'IRL',
    Numeric: 372,
    'English short name': 'Ireland',
    'French short name': "Irlande (l')",
    'Avarni name (Original)': 'ireland',
    'Avarni name (Updated)': 'Ireland',
    'Alternate Spellings': 'Republic of Ireland, Éire',
  },
  {
    'Alpha-2 code': 'IM',
    'Alpha-3 code': 'IMN',
    Numeric: 833,
    'English short name': 'Isle of Man',
    'French short name': 'Île de Man',
    'Avarni name (Original)': '',
    'Avarni name (Updated)': 'Isle Of Man',
    'Alternate Spellings': 'The Isle of Man',
  },
  {
    'Alpha-2 code': 'IL',
    'Alpha-3 code': 'ISR',
    Numeric: 376,
    'English short name': 'Israel',
    'French short name': 'Israël',
    'Avarni name (Original)': 'israel',
    'Avarni name (Updated)': 'Israel',
    'Alternate Spellings': 'State of Israel, Yisrael',
  },
  {
    'Alpha-2 code': 'IT',
    'Alpha-3 code': 'ITA',
    Numeric: 380,
    'English short name': 'Italy',
    'French short name': "Italie (l')",
    'Avarni name (Original)': 'italy',
    'Avarni name (Updated)': 'Italy',
    'Alternate Spellings': 'Italian Republic, Italia',
  },
  {
    'Alpha-2 code': 'JM',
    'Alpha-3 code': 'JAM',
    Numeric: 388,
    'English short name': 'Jamaica',
    'French short name': 'Jamaïque (la)',
    'Avarni name (Original)': 'jamaica',
    'Avarni name (Updated)': 'Jamaica',
    'Alternate Spellings': '',
  },
  {
    'Alpha-2 code': 'JP',
    'Alpha-3 code': 'JPN',
    Numeric: 392,
    'English short name': 'Japan',
    'French short name': 'Japon (le)',
    'Avarni name (Original)': 'japan',
    'Avarni name (Updated)': 'Japan',
    'Alternate Spellings': 'Nippon, Nihon',
  },
  {
    'Alpha-2 code': 'JE',
    'Alpha-3 code': 'JEY',
    Numeric: 832,
    'English short name': 'Jersey',
    'French short name': 'Jersey',
    'Avarni name (Original)': '',
    'Avarni name (Updated)': 'Jersey',
    'Alternate Spellings': 'Bailiwick of Jersey, Jèrri',
  },
  {
    'Alpha-2 code': 'JO',
    'Alpha-3 code': 'JOR',
    Numeric: 400,
    'English short name': 'Jordan',
    'French short name': 'Jordanie (la)',
    'Avarni name (Original)': 'jordan',
    'Avarni name (Updated)': 'Jordan',
    'Alternate Spellings':
      'Hashemite Kingdom of Jordan, Al-Mamlakah al-Urdunniyyah al-Hashimiyyah, Transjordan',
  },
  {
    'Alpha-2 code': 'KZ',
    'Alpha-3 code': 'KAZ',
    Numeric: 398,
    'English short name': 'Kazakhstan',
    'French short name': 'Kazakhstan (le)',
    'Avarni name (Original)': 'kazakhstan',
    'Avarni name (Updated)': 'Kazakhstan',
    'Alternate Spellings': 'Republic of Kazakhstan, Qazaqstan',
  },
  {
    'Alpha-2 code': 'KE',
    'Alpha-3 code': 'KEN',
    Numeric: 404,
    'English short name': 'Kenya',
    'French short name': 'Kenya (le)',
    'Avarni name (Original)': 'kenya',
    'Avarni name (Updated)': 'Kenya',
    'Alternate Spellings': 'Republic of Kenya',
  },
  {
    'Alpha-2 code': 'KI',
    'Alpha-3 code': 'KIR',
    Numeric: 296,
    'English short name': 'Kiribati',
    'French short name': 'Kiribati',
    'Avarni name (Original)': 'kiribati',
    'Avarni name (Updated)': 'Kiribati',
    'Alternate Spellings': 'Republic of Kiribati',
  },
  {
    'Alpha-2 code': 'KP',
    'Alpha-3 code': 'PRK',
    Numeric: 408,
    'English short name': "Korea (the Democratic People's Republic of)",
    'French short name': 'Corée (la République populaire démocratique de)',
    'Avarni name (Original)': 'north korea',
    'Avarni name (Updated)': 'North Korea',
    'Alternate Spellings':
      "The Democratic People's Republic of Korea, Democratic People's Republic of Korea, DPRK",
  },
  {
    'Alpha-2 code': 'KR',
    'Alpha-3 code': 'KOR',
    Numeric: 410,
    'English short name': 'Korea (the Republic of)',
    'French short name': 'Corée (la République de)',
    'Avarni name (Original)': 'south korea',
    'Avarni name (Updated)': 'South Korea',
    'Alternate Spellings': 'the Republic of Korea, Republic of Korea, ROK',
  },
  {
    'Alpha-2 code': '',
    'Alpha-3 code': '',
    Numeric: null,
    'English short name': '',
    'French short name': '',
    'Avarni name (Original)': 'kosovo',
    'Avarni name (Updated)': 'Kosovo',
    'Alternate Spellings': 'Republic of Kosovo',
  },
  {
    'Alpha-2 code': 'KW',
    'Alpha-3 code': 'KWT',
    Numeric: 414,
    'English short name': 'Kuwait',
    'French short name': 'Koweït (le)',
    'Avarni name (Original)': 'kuwait',
    'Avarni name (Updated)': 'Kuwait',
    'Alternate Spellings': 'State of Kuwait',
  },
  {
    'Alpha-2 code': 'KG',
    'Alpha-3 code': 'KGZ',
    Numeric: 417,
    'English short name': 'Kyrgyzstan',
    'French short name': 'Kirghizistan (le)',
    'Avarni name (Original)': 'kyrgyzstan',
    'Avarni name (Updated)': 'Kyrgyzstan',
    'Alternate Spellings': 'Kyrgyz Republic',
  },
  {
    'Alpha-2 code': 'LA',
    'Alpha-3 code': 'LAO',
    Numeric: 418,
    'English short name': "Lao People's Democratic Republic (the)",
    'French short name': 'Lao (la République démocratique populaire)',
    'Avarni name (Original)': 'laos',
    'Avarni name (Updated)': 'Laos',
    'Alternate Spellings':
      "The Lao People's Democratic Republic, Lao People's Democratic Republic",
  },
  {
    'Alpha-2 code': 'LV',
    'Alpha-3 code': 'LVA',
    Numeric: 428,
    'English short name': 'Latvia',
    'French short name': 'Lettonie (la)',
    'Avarni name (Original)': 'latvia',
    'Avarni name (Updated)': 'Latvia',
    'Alternate Spellings': 'Republic of Latvia, Latvija',
  },
  {
    'Alpha-2 code': 'LB',
    'Alpha-3 code': 'LBN',
    Numeric: 422,
    'English short name': 'Lebanon',
    'French short name': 'Liban (le)',
    'Avarni name (Original)': 'lebanon',
    'Avarni name (Updated)': 'Lebanon',
    'Alternate Spellings': 'Lebanese Republic, Lubnan',
  },
  {
    'Alpha-2 code': 'LS',
    'Alpha-3 code': 'LSO',
    Numeric: 426,
    'English short name': 'Lesotho',
    'French short name': 'Lesotho (le)',
    'Avarni name (Original)': 'lesotho',
    'Avarni name (Updated)': 'Lesotho',
    'Alternate Spellings': 'Kingdom of Lesotho',
  },
  {
    'Alpha-2 code': 'LR',
    'Alpha-3 code': 'LBR',
    Numeric: 430,
    'English short name': 'Liberia',
    'French short name': 'Libéria (le)',
    'Avarni name (Original)': 'liberia',
    'Avarni name (Updated)': 'Liberia',
    'Alternate Spellings': 'Republic of Liberia',
  },
  {
    'Alpha-2 code': 'LY',
    'Alpha-3 code': 'LBY',
    Numeric: 434,
    'English short name': 'Libya',
    'French short name': 'Libye (la)',
    'Avarni name (Original)': 'libya',
    'Avarni name (Updated)': 'Libya',
    'Alternate Spellings': 'State of Libya',
  },
  {
    'Alpha-2 code': 'LI',
    'Alpha-3 code': 'LIE',
    Numeric: 438,
    'English short name': 'Liechtenstein',
    'French short name': 'Liechtenstein (le)',
    'Avarni name (Original)': 'liechtenstein',
    'Avarni name (Updated)': 'Liechtenstein',
    'Alternate Spellings': 'Principality of Liechtenstein',
  },
  {
    'Alpha-2 code': 'LT',
    'Alpha-3 code': 'LTU',
    Numeric: 440,
    'English short name': 'Lithuania',
    'French short name': 'Lituanie (la)',
    'Avarni name (Original)': 'lithuania',
    'Avarni name (Updated)': 'Lithuania',
    'Alternate Spellings': 'Republic of Lithuania, Lietuva',
  },
  {
    'Alpha-2 code': 'LU',
    'Alpha-3 code': 'LUX',
    Numeric: 442,
    'English short name': 'Luxembourg',
    'French short name': 'Luxembourg (le)',
    'Avarni name (Original)': 'luxembourg',
    'Avarni name (Updated)': 'Luxembourg',
    'Alternate Spellings': 'Grand Duchy of Luxembourg',
  },
  {
    'Alpha-2 code': 'MO',
    'Alpha-3 code': 'MAC',
    Numeric: 446,
    'English short name': 'Macao',
    'French short name': 'Macao',
    'Avarni name (Original)': 'macau',
    'Avarni name (Updated)': 'Macau',
    'Alternate Spellings': 'Macao',
  },
  {
    'Alpha-2 code': 'MG',
    'Alpha-3 code': 'MDG',
    Numeric: 450,
    'English short name': 'Madagascar',
    'French short name': 'Madagascar',
    'Avarni name (Original)': 'madagascar',
    'Avarni name (Updated)': 'Madagascar',
    'Alternate Spellings': 'Republic of Madagascar',
  },
  {
    'Alpha-2 code': 'MW',
    'Alpha-3 code': 'MWI',
    Numeric: 454,
    'English short name': 'Malawi',
    'French short name': 'Malawi (le)',
    'Avarni name (Original)': 'malawi',
    'Avarni name (Updated)': 'Malawi',
    'Alternate Spellings': 'Republic of Malawi',
  },
  {
    'Alpha-2 code': 'MY',
    'Alpha-3 code': 'MYS',
    Numeric: 458,
    'English short name': 'Malaysia',
    'French short name': 'Malaisie (la)',
    'Avarni name (Original)': 'malaysia',
    'Avarni name (Updated)': 'Malaysia',
    'Alternate Spellings': 'Federation of Malaysia, Malaya',
  },
  {
    'Alpha-2 code': 'MV',
    'Alpha-3 code': 'MDV',
    Numeric: 462,
    'English short name': 'Maldives',
    'French short name': 'Maldives (les)',
    'Avarni name (Original)': 'maldives',
    'Avarni name (Updated)': 'Maldives',
    'Alternate Spellings': 'Republic of Maldives',
  },
  {
    'Alpha-2 code': 'ML',
    'Alpha-3 code': 'MLI',
    Numeric: 466,
    'English short name': 'Mali',
    'French short name': 'Mali (le)',
    'Avarni name (Original)': 'mali',
    'Avarni name (Updated)': 'Mali',
    'Alternate Spellings': 'Republic of Mali',
  },
  {
    'Alpha-2 code': 'MT',
    'Alpha-3 code': 'MLT',
    Numeric: 470,
    'English short name': 'Malta',
    'French short name': 'Malte',
    'Avarni name (Original)': 'malta',
    'Avarni name (Updated)': 'Malta',
    'Alternate Spellings': "Republic of Malta, Repubblika ta' Malta",
  },
  {
    'Alpha-2 code': 'MH',
    'Alpha-3 code': 'MHL',
    Numeric: 584,
    'English short name': 'Marshall Islands (the)',
    'French short name': 'Marshall (les Îles)',
    'Avarni name (Original)': 'marshall islands',
    'Avarni name (Updated)': 'Marshall Islands',
    'Alternate Spellings':
      'Republic of the Marshall Islands, The Marshall Islands',
  },
  {
    'Alpha-2 code': 'MQ',
    'Alpha-3 code': 'MTQ',
    Numeric: 474,
    'English short name': 'Martinique',
    'French short name': 'Martinique (la)',
    'Avarni name (Original)': '',
    'Avarni name (Updated)': 'Martinique',
    'Alternate Spellings': 'Department of Martinique',
  },
  {
    'Alpha-2 code': 'MR',
    'Alpha-3 code': 'MRT',
    Numeric: 478,
    'English short name': 'Mauritania',
    'French short name': 'Mauritanie (la)',
    'Avarni name (Original)': 'mauritania',
    'Avarni name (Updated)': 'Mauritania',
    'Alternate Spellings': 'Islamic Republic of Mauritania, Mūrītāniyā',
  },
  {
    'Alpha-2 code': 'MU',
    'Alpha-3 code': 'MUS',
    Numeric: 480,
    'English short name': 'Mauritius',
    'French short name': 'Maurice',
    'Avarni name (Original)': 'mauritius',
    'Avarni name (Updated)': 'Mauritius',
    'Alternate Spellings': 'Republic of Mauritius',
  },
  {
    'Alpha-2 code': 'YT',
    'Alpha-3 code': 'MYT',
    Numeric: 175,
    'English short name': 'Mayotte',
    'French short name': 'Mayotte',
    'Avarni name (Original)': '',
    'Avarni name (Updated)': 'Mayotte',
    'Alternate Spellings': 'Department of Mayotte',
  },
  {
    'Alpha-2 code': 'MX',
    'Alpha-3 code': 'MEX',
    Numeric: 484,
    'English short name': 'Mexico',
    'French short name': 'Mexique (le)',
    'Avarni name (Original)': 'mexico',
    'Avarni name (Updated)': 'Mexico',
    'Alternate Spellings': 'United Mexican States, México',
  },
  {
    'Alpha-2 code': 'FM',
    'Alpha-3 code': 'FSM',
    Numeric: 583,
    'English short name': 'Micronesia (Federated States of)',
    'French short name': 'Micronésie (États fédérés de)',
    'Avarni name (Original)': 'micronesia',
    'Avarni name (Updated)': 'Micronesia',
    'Alternate Spellings':
      'The Federated States of Micronesia, Federated States of Micronesia',
  },
  {
    'Alpha-2 code': 'MD',
    'Alpha-3 code': 'MDA',
    Numeric: 498,
    'English short name': 'Moldova (the Republic of)',
    'French short name': 'Moldova (la République de)',
    'Avarni name (Original)': 'moldova',
    'Avarni name (Updated)': 'Moldova',
    'Alternate Spellings':
      'Republic of Moldova, Moldavia, The Republic of Moldova',
  },
  {
    'Alpha-2 code': 'MC',
    'Alpha-3 code': 'MCO',
    Numeric: 492,
    'English short name': 'Monaco',
    'French short name': 'Monaco',
    'Avarni name (Original)': 'monaco',
    'Avarni name (Updated)': 'Monaco',
    'Alternate Spellings': 'Principality of Monaco',
  },
  {
    'Alpha-2 code': 'MN',
    'Alpha-3 code': 'MNG',
    Numeric: 496,
    'English short name': 'Mongolia',
    'French short name': 'Mongolie (la)',
    'Avarni name (Original)': 'mongolia',
    'Avarni name (Updated)': 'Mongolia',
    'Alternate Spellings': '',
  },
  {
    'Alpha-2 code': 'ME',
    'Alpha-3 code': 'MNE',
    Numeric: 499,
    'English short name': 'Montenegro',
    'French short name': 'Monténégro (le)',
    'Avarni name (Original)': 'montenegro',
    'Avarni name (Updated)': 'Montenegro',
    'Alternate Spellings': 'Republic of Montenegro',
  },
  {
    'Alpha-2 code': 'MS',
    'Alpha-3 code': 'MSR',
    Numeric: 500,
    'English short name': 'Montserrat',
    'French short name': 'Montserrat',
    'Avarni name (Original)': '',
    'Avarni name (Updated)': 'Montserrat',
    'Alternate Spellings': '',
  },
  {
    'Alpha-2 code': 'MA',
    'Alpha-3 code': 'MAR',
    Numeric: 504,
    'English short name': 'Morocco',
    'French short name': 'Maroc (le)',
    'Avarni name (Original)': 'morocco',
    'Avarni name (Updated)': 'Morocco',
    'Alternate Spellings': 'Kingdom of Morocco, Maroc',
  },
  {
    'Alpha-2 code': 'MZ',
    'Alpha-3 code': 'MOZ',
    Numeric: 508,
    'English short name': 'Mozambique',
    'French short name': 'Mozambique (le)',
    'Avarni name (Original)': 'mozambique',
    'Avarni name (Updated)': 'Mozambique',
    'Alternate Spellings': 'Republic of Mozambique',
  },
  {
    'Alpha-2 code': 'MM',
    'Alpha-3 code': 'MMR',
    Numeric: 104,
    'English short name': 'Myanmar',
    'French short name': 'Myanmar (le)',
    'Avarni name (Original)': 'myanmar',
    'Avarni name (Updated)': 'Myanmar',
    'Alternate Spellings': 'Republic of the Union of Myanmar, Burma',
  },
  {
    'Alpha-2 code': 'NA',
    'Alpha-3 code': 'NAM',
    Numeric: 516,
    'English short name': 'Namibia',
    'French short name': 'Namibie (la)',
    'Avarni name (Original)': 'namibia',
    'Avarni name (Updated)': 'Namibia',
    'Alternate Spellings': 'Nambiya, Namibië',
  },
  {
    'Alpha-2 code': 'NR',
    'Alpha-3 code': 'NRU',
    Numeric: 520,
    'English short name': 'Nauru',
    'French short name': 'Nauru',
    'Avarni name (Original)': 'nauru',
    'Avarni name (Updated)': 'Nauru',
    'Alternate Spellings': 'Naoero',
  },
  {
    'Alpha-2 code': 'NP',
    'Alpha-3 code': 'NPL',
    Numeric: 524,
    'English short name': 'Nepal',
    'French short name': 'Népal (le)',
    'Avarni name (Original)': 'nepal',
    'Avarni name (Updated)': 'Nepal',
    'Alternate Spellings': 'Nepāl, Federal Democratic Republic of Nepal',
  },
  {
    'Alpha-2 code': 'NL',
    'Alpha-3 code': 'NLD',
    Numeric: 528,
    'English short name': 'Netherlands (Kingdom of the)',
    'French short name': 'Pays-Bas (Royaume des)',
    'Avarni name (Original)': 'netherlands',
    'Avarni name (Updated)': 'Netherlands',
    'Alternate Spellings': 'Holland, Kingdom of the Netherlands, Nederland',
  },
  {
    'Alpha-2 code': 'NC',
    'Alpha-3 code': 'NCL',
    Numeric: 540,
    'English short name': 'New Caledonia',
    'French short name': 'Nouvelle-Calédonie (la)',
    'Avarni name (Original)': 'new caledonia',
    'Avarni name (Updated)': 'New Caledonia',
    'Alternate Spellings': 'Nouvelle-Calédonie',
  },
  {
    'Alpha-2 code': 'NZ',
    'Alpha-3 code': 'NZL',
    Numeric: 554,
    'English short name': 'New Zealand',
    'French short name': 'Nouvelle-Zélande (la)',
    'Avarni name (Original)': 'new zealand',
    'Avarni name (Updated)': 'New Zealand',
    'Alternate Spellings': 'Aotearoa',
  },
  {
    'Alpha-2 code': 'NI',
    'Alpha-3 code': 'NIC',
    Numeric: 558,
    'English short name': 'Nicaragua',
    'French short name': 'Nicaragua (le)',
    'Avarni name (Original)': 'nicaragua',
    'Avarni name (Updated)': 'Nicaragua',
    'Alternate Spellings': 'Republic of Nicaragua, República de Nicaragua',
  },
  {
    'Alpha-2 code': 'NE',
    'Alpha-3 code': 'NER',
    Numeric: 562,
    'English short name': 'Niger (the)',
    'French short name': 'Niger (le)',
    'Avarni name (Original)': 'niger',
    'Avarni name (Updated)': 'Niger',
    'Alternate Spellings': 'Republic of Niger, République du Niger, The Niger',
  },
  {
    'Alpha-2 code': 'NG',
    'Alpha-3 code': 'NGA',
    Numeric: 566,
    'English short name': 'Nigeria',
    'French short name': 'Nigéria (le)',
    'Avarni name (Original)': 'nigeria',
    'Avarni name (Updated)': 'Nigeria',
    'Alternate Spellings': 'Federal Republic of Nigeria',
  },
  {
    'Alpha-2 code': 'NU',
    'Alpha-3 code': 'NIU',
    Numeric: 570,
    'English short name': 'Niue',
    'French short name': 'Niue',
    'Avarni name (Original)': '',
    'Avarni name (Updated)': 'Niue',
    'Alternate Spellings': 'Niue Island',
  },
  {
    'Alpha-2 code': 'NF',
    'Alpha-3 code': 'NFK',
    Numeric: 574,
    'English short name': 'Norfolk Island',
    'French short name': "Norfolk (l'Île)",
    'Avarni name (Original)': '',
    'Avarni name (Updated)': 'Norfolk Island',
    'Alternate Spellings': '',
  },
  {
    'Alpha-2 code': 'MK',
    'Alpha-3 code': 'MKD',
    Numeric: 807,
    'English short name': 'North Macedonia',
    'French short name': 'Macédoine du Nord (la)',
    'Avarni name (Original)': 'north macedonia',
    'Avarni name (Updated)': 'North Macedonia',
    'Alternate Spellings': 'Republic of North Macedonia, Severna Makedonija',
  },
  {
    'Alpha-2 code': 'MP',
    'Alpha-3 code': 'MNP',
    Numeric: 580,
    'English short name': 'Northern Mariana Islands (the)',
    'French short name': 'Mariannes du Nord (les Îles)',
    'Avarni name (Original)': '',
    'Avarni name (Updated)': 'Northern Mariana Islands',
    'Alternate Spellings':
      'Commonwealth of the Northern Mariana Islands, The Northern Mariana Islands',
  },
  {
    'Alpha-2 code': 'NO',
    'Alpha-3 code': 'NOR',
    Numeric: 578,
    'English short name': 'Norway',
    'French short name': 'Norvège (la)',
    'Avarni name (Original)': 'norway',
    'Avarni name (Updated)': 'Norway',
    'Alternate Spellings': 'Kingdom of Norway, Norge',
  },
  {
    'Alpha-2 code': 'OM',
    'Alpha-3 code': 'OMN',
    Numeric: 512,
    'English short name': 'Oman',
    'French short name': 'Oman',
    'Avarni name (Original)': 'oman',
    'Avarni name (Updated)': 'Oman',
    'Alternate Spellings': 'Sultanate of Oman, Salṭanat ʻUmān',
  },
  {
    'Alpha-2 code': 'PK',
    'Alpha-3 code': 'PAK',
    Numeric: 586,
    'English short name': 'Pakistan',
    'French short name': 'Pakistan (le)',
    'Avarni name (Original)': 'pakistan',
    'Avarni name (Updated)': 'Pakistan',
    'Alternate Spellings': 'Islamic Republic of Pakistan',
  },
  {
    'Alpha-2 code': 'PW',
    'Alpha-3 code': 'PLW',
    Numeric: 585,
    'English short name': 'Palau',
    'French short name': 'Palaos (les)',
    'Avarni name (Original)': 'palau',
    'Avarni name (Updated)': 'Palau',
    'Alternate Spellings': 'Republic of Palau, Beluu er a Belau',
  },
  {
    'Alpha-2 code': 'PS',
    'Alpha-3 code': 'PSE',
    Numeric: 275,
    'English short name': 'Palestine, State of',
    'French short name': 'Palestine, État de',
    'Avarni name (Original)': 'palestine',
    'Avarni name (Updated)': 'Palestine',
    'Alternate Spellings': 'State of Palestine',
  },
  {
    'Alpha-2 code': 'PA',
    'Alpha-3 code': 'PAN',
    Numeric: 591,
    'English short name': 'Panama',
    'French short name': 'Panama (le)',
    'Avarni name (Original)': 'panama',
    'Avarni name (Updated)': 'Panama',
    'Alternate Spellings': 'Republic of Panama, República de Panamá',
  },
  {
    'Alpha-2 code': 'PG',
    'Alpha-3 code': 'PNG',
    Numeric: 598,
    'English short name': 'Papua New Guinea',
    'French short name': 'Papouasie-Nouvelle-Guinée (la)',
    'Avarni name (Original)': 'papua new guinea',
    'Avarni name (Updated)': 'Papua New Guinea',
    'Alternate Spellings': 'Independent State of Papua New Guinea',
  },
  {
    'Alpha-2 code': 'PY',
    'Alpha-3 code': 'PRY',
    Numeric: 600,
    'English short name': 'Paraguay',
    'French short name': 'Paraguay (le)',
    'Avarni name (Original)': 'paraguay',
    'Avarni name (Updated)': 'Paraguay',
    'Alternate Spellings': 'Republic of Paraguay, República del Paraguay',
  },
  {
    'Alpha-2 code': 'PE',
    'Alpha-3 code': 'PER',
    Numeric: 604,
    'English short name': 'Peru',
    'French short name': 'Pérou (le)',
    'Avarni name (Original)': 'peru',
    'Avarni name (Updated)': 'Peru',
    'Alternate Spellings': 'Republic of Peru, República del Perú',
  },
  {
    'Alpha-2 code': 'PH',
    'Alpha-3 code': 'PHL',
    Numeric: 608,
    'English short name': 'Philippines (the)',
    'French short name': 'Philippines (les)',
    'Avarni name (Original)': 'philippines',
    'Avarni name (Updated)': 'Philippines',
    'Alternate Spellings':
      'Republic of the Philippines, Pilipinas, The Philippines',
  },
  {
    'Alpha-2 code': 'PN',
    'Alpha-3 code': 'PCN',
    Numeric: 612,
    'English short name': 'Pitcairn',
    'French short name': 'Pitcairn',
    'Avarni name (Original)': '',
    'Avarni name (Updated)': 'Pitcairn',
    'Alternate Spellings': 'Pitcairn Islands',
  },
  {
    'Alpha-2 code': 'PL',
    'Alpha-3 code': 'POL',
    Numeric: 616,
    'English short name': 'Poland',
    'French short name': 'Pologne (la)',
    'Avarni name (Original)': 'poland',
    'Avarni name (Updated)': 'Poland',
    'Alternate Spellings': 'Republic of Poland, Rzeczpospolita Polska',
  },
  {
    'Alpha-2 code': 'PT',
    'Alpha-3 code': 'PRT',
    Numeric: 620,
    'English short name': 'Portugal',
    'French short name': 'Portugal (le)',
    'Avarni name (Original)': 'portugal',
    'Avarni name (Updated)': 'Portugal',
    'Alternate Spellings': 'Portuguese Republic, República Portuguesa',
  },
  {
    'Alpha-2 code': 'PR',
    'Alpha-3 code': 'PRI',
    Numeric: 630,
    'English short name': 'Puerto Rico',
    'French short name': 'Porto Rico',
    'Avarni name (Original)': 'puerto rico',
    'Avarni name (Updated)': 'Puerto Rico',
    'Alternate Spellings': 'Commonwealth of Puerto Rico',
  },
  {
    'Alpha-2 code': 'QA',
    'Alpha-3 code': 'QAT',
    Numeric: 634,
    'English short name': 'Qatar',
    'French short name': 'Qatar (le)',
    'Avarni name (Original)': 'qatar',
    'Avarni name (Updated)': 'Qatar',
    'Alternate Spellings': 'State of Qatar, Dawlat Qaṭar',
  },
  {
    'Alpha-2 code': 'RO',
    'Alpha-3 code': 'ROU',
    Numeric: 642,
    'English short name': 'Romania',
    'French short name': 'Roumanie (la)',
    'Avarni name (Original)': 'romania',
    'Avarni name (Updated)': 'Romania',
    'Alternate Spellings': 'Rumania, Republic of Romania, România',
  },
  {
    'Alpha-2 code': 'RU',
    'Alpha-3 code': 'RUS',
    Numeric: 643,
    'English short name': 'Russian Federation (the)',
    'French short name': 'Russie (la Fédération de)',
    'Avarni name (Original)': 'russia',
    'Avarni name (Updated)': 'Russia',
    'Alternate Spellings':
      'Russian Federation, Rossiyskaya Federatsiya, The Russian Federation',
  },
  {
    'Alpha-2 code': 'RW',
    'Alpha-3 code': 'RWA',
    Numeric: 646,
    'English short name': 'Rwanda',
    'French short name': 'Rwanda (le)',
    'Avarni name (Original)': 'rwanda',
    'Avarni name (Updated)': 'Rwanda',
    'Alternate Spellings': 'Republic of Rwanda, République du Rwanda',
  },
  {
    'Alpha-2 code': 'RE',
    'Alpha-3 code': 'REU',
    Numeric: 638,
    'English short name': 'Réunion',
    'French short name': 'Réunion (La)',
    'Avarni name (Original)': '',
    'Avarni name (Updated)': 'Réunion',
    'Alternate Spellings': 'La Réunion',
  },
  {
    'Alpha-2 code': 'BL',
    'Alpha-3 code': 'BLM',
    Numeric: 652,
    'English short name': 'Saint Barthélemy',
    'French short name': 'Saint-Barthélemy',
    'Avarni name (Original)': '',
    'Avarni name (Updated)': 'Saint Barthélemy',
    'Alternate Spellings':
      'St. Barts, St. Barths, St Barthélemy, St. Barthélemy',
  },
  {
    'Alpha-2 code': 'SH',
    'Alpha-3 code': 'SHN',
    Numeric: 654,
    'English short name': 'Saint Helena, Ascension and Tristan da Cunha',
    'French short name': 'Sainte-Hélène, Ascension et Tristan da Cunha',
    'Avarni name (Original)': '',
    'Avarni name (Updated)': 'Saint Helena',
    'Alternate Spellings': 'St. Helena, St Helena',
  },
  {
    'Alpha-2 code': 'KN',
    'Alpha-3 code': 'KNA',
    Numeric: 659,
    'English short name': 'Saint Kitts and Nevis',
    'French short name': 'Saint-Kitts-et-Nevis',
    'Avarni name (Original)': 'st kitts & nevis',
    'Avarni name (Updated)': 'Saint Kitts & Nevis',
    'Alternate Spellings':
      'Federation of Saint Christopher and Nevis, st. kitts & nevis, st kitts & nevis',
  },
  {
    'Alpha-2 code': 'LC',
    'Alpha-3 code': 'LCA',
    Numeric: 662,
    'English short name': 'Saint Lucia',
    'French short name': 'Sainte-Lucie',
    'Avarni name (Original)': 'st lucia',
    'Avarni name (Updated)': 'Saint Lucia',
    'Alternate Spellings': 'St. Lucia, st lucia',
  },
  {
    'Alpha-2 code': 'MF',
    'Alpha-3 code': 'MAF',
    Numeric: 663,
    'English short name': 'Saint Martin (French part)',
    'French short name': 'Saint-Martin (partie française)',
    'Avarni name (Original)': '',
    'Avarni name (Updated)': 'Saint Martin',
    'Alternate Spellings': 'St. Maarten, St. Martin, St Martin',
  },
  {
    'Alpha-2 code': 'PM',
    'Alpha-3 code': 'SPM',
    Numeric: 666,
    'English short name': 'Saint Pierre and Miquelon',
    'French short name': 'Saint-Pierre-et-Miquelon',
    'Avarni name (Original)': '',
    'Avarni name (Updated)': 'Saint Pierre And Miquelon',
    'Alternate Spellings': 'St. Pierre and Miquelon, St Pierre and Miquelon',
  },
  {
    'Alpha-2 code': 'VC',
    'Alpha-3 code': 'VCT',
    Numeric: 670,
    'English short name': 'Saint Vincent and the Grenadines',
    'French short name': 'Saint-Vincent-et-les Grenadines',
    'Avarni name (Original)': 'saint vincent & the grenadines',
    'Avarni name (Updated)': 'Saint Vincent & The Grenadines',
    'Alternate Spellings':
      'St. Vincent and the Grenadines, St Vincent and the Grenadines',
  },
  {
    'Alpha-2 code': 'WS',
    'Alpha-3 code': 'WSM',
    Numeric: 882,
    'English short name': 'Samoa',
    'French short name': 'Samoa (le)',
    'Avarni name (Original)': 'samoa',
    'Avarni name (Updated)': 'Samoa',
    'Alternate Spellings':
      "Independent State of Samoa, Malo Sa'oloto Tuto'atasi o Sāmoa",
  },
  {
    'Alpha-2 code': 'SM',
    'Alpha-3 code': 'SMR',
    Numeric: 674,
    'English short name': 'San Marino',
    'French short name': 'Saint-Marin',
    'Avarni name (Original)': 'san marino',
    'Avarni name (Updated)': 'San Marino',
    'Alternate Spellings':
      'Republic of San Marino, Serenissima Repubblica di San Marino',
  },
  {
    'Alpha-2 code': 'ST',
    'Alpha-3 code': 'STP',
    Numeric: 678,
    'English short name': 'Sao Tome and Principe',
    'French short name': 'Sao Tomé-et-Principe',
    'Avarni name (Original)': 'sao tome & principe',
    'Avarni name (Updated)': 'Sao Tome & Principe',
    'Alternate Spellings':
      'Democratic Republic of Sao Tome and Principe, Sao Tome and Principe',
  },
  {
    'Alpha-2 code': 'SA',
    'Alpha-3 code': 'SAU',
    Numeric: 682,
    'English short name': 'Saudi Arabia',
    'French short name': "Arabie saoudite (l')",
    'Avarni name (Original)': 'saudi arabia',
    'Avarni name (Updated)': 'Saudi Arabia',
    'Alternate Spellings': 'Kingdom of Saudi Arabia',
  },
  {
    'Alpha-2 code': 'SN',
    'Alpha-3 code': 'SEN',
    Numeric: 686,
    'English short name': 'Senegal',
    'French short name': 'Sénégal (le)',
    'Avarni name (Original)': 'senegal',
    'Avarni name (Updated)': 'Senegal',
    'Alternate Spellings': 'Republic of Senegal, République du Sénégal',
  },
  {
    'Alpha-2 code': 'RS',
    'Alpha-3 code': 'SRB',
    Numeric: 688,
    'English short name': 'Serbia',
    'French short name': 'Serbie (la)',
    'Avarni name (Original)': 'serbia',
    'Avarni name (Updated)': 'Serbia',
    'Alternate Spellings': 'Republic of Serbia, Republika Srbija',
  },
  {
    'Alpha-2 code': 'SC',
    'Alpha-3 code': 'SYC',
    Numeric: 690,
    'English short name': 'Seychelles',
    'French short name': 'Seychelles (les)',
    'Avarni name (Original)': 'seychelles',
    'Avarni name (Updated)': 'Seychelles',
    'Alternate Spellings': 'Republic of Seychelles',
  },
  {
    'Alpha-2 code': 'SL',
    'Alpha-3 code': 'SLE',
    Numeric: 694,
    'English short name': 'Sierra Leone',
    'French short name': 'Sierra Leone (la)',
    'Avarni name (Original)': 'sierra leone',
    'Avarni name (Updated)': 'Sierra Leone',
    'Alternate Spellings': 'Republic of Sierra Leone, Sa Lone',
  },
  {
    'Alpha-2 code': 'SG',
    'Alpha-3 code': 'SGP',
    Numeric: 702,
    'English short name': 'Singapore',
    'French short name': 'Singapour',
    'Avarni name (Original)': 'singapore',
    'Avarni name (Updated)': 'Singapore',
    'Alternate Spellings': 'Republic of Singapore',
  },
  {
    'Alpha-2 code': 'SX',
    'Alpha-3 code': 'SXM',
    Numeric: 534,
    'English short name': 'Sint Maarten (Dutch part)',
    'French short name': 'Saint-Martin (partie néerlandaise)',
    'Avarni name (Original)': '',
    'Avarni name (Updated)': 'Sint Maarten',
    'Alternate Spellings': '',
  },
  {
    'Alpha-2 code': 'SK',
    'Alpha-3 code': 'SVK',
    Numeric: 703,
    'English short name': 'Slovakia',
    'French short name': 'Slovaquie (la)',
    'Avarni name (Original)': 'slovakia',
    'Avarni name (Updated)': 'Slovakia',
    'Alternate Spellings': 'Slovak Republic',
  },
  {
    'Alpha-2 code': 'SI',
    'Alpha-3 code': 'SVN',
    Numeric: 705,
    'English short name': 'Slovenia',
    'French short name': 'Slovénie (la)',
    'Avarni name (Original)': 'slovenia',
    'Avarni name (Updated)': 'Slovenia',
    'Alternate Spellings': 'Republic of Slovenia',
  },
  {
    'Alpha-2 code': 'SB',
    'Alpha-3 code': 'SLB',
    Numeric: 90,
    'English short name': 'Solomon Islands',
    'French short name': 'Salomon (les Îles)',
    'Avarni name (Original)': 'solomon islands',
    'Avarni name (Updated)': 'Solomon Islands',
    'Alternate Spellings': 'Salomon Islands',
  },
  {
    'Alpha-2 code': 'SO',
    'Alpha-3 code': 'SOM',
    Numeric: 706,
    'English short name': 'Somalia',
    'French short name': 'Somalie (la)',
    'Avarni name (Original)': 'somalia',
    'Avarni name (Updated)': 'Somalia',
    'Alternate Spellings': 'Federal Republic of Somalia',
  },
  {
    'Alpha-2 code': 'ZA',
    'Alpha-3 code': 'ZAF',
    Numeric: 710,
    'English short name': 'South Africa',
    'French short name': "Afrique du Sud (l')",
    'Avarni name (Original)': 'south africa',
    'Avarni name (Updated)': 'South Africa',
    'Alternate Spellings': 'Republic of South Africa',
  },
  {
    'Alpha-2 code': 'GS',
    'Alpha-3 code': 'SGS',
    Numeric: 239,
    'English short name': 'South Georgia and the South Sandwich Islands',
    'French short name': 'Géorgie du Sud-et-les Îles Sandwich du Sud (la)',
    'Avarni name (Original)': '',
    'Avarni name (Updated)': 'South Georgia',
    'Alternate Spellings':
      'South Georgia and the South Sandwich Islands, South Georgia & the South Sandwich Islands',
  },
  {
    'Alpha-2 code': 'SS',
    'Alpha-3 code': 'SSD',
    Numeric: 728,
    'English short name': 'South Sudan',
    'French short name': 'Soudan du Sud (le)',
    'Avarni name (Original)': 'south sudan',
    'Avarni name (Updated)': 'South Sudan',
    'Alternate Spellings': 'Republic of South Sudan',
  },
  {
    'Alpha-2 code': 'ES',
    'Alpha-3 code': 'ESP',
    Numeric: 724,
    'English short name': 'Spain',
    'French short name': "Espagne (l')",
    'Avarni name (Original)': 'spain',
    'Avarni name (Updated)': 'Spain',
    'Alternate Spellings': 'Kingdom of Spain',
  },
  {
    'Alpha-2 code': 'LK',
    'Alpha-3 code': 'LKA',
    Numeric: 144,
    'English short name': 'Sri Lanka',
    'French short name': 'Sri Lanka',
    'Avarni name (Original)': 'sri lanka',
    'Avarni name (Updated)': 'Sri Lanka',
    'Alternate Spellings': 'Democratic Socialist Republic of Sri Lanka',
  },
  {
    'Alpha-2 code': 'SD',
    'Alpha-3 code': 'SDN',
    Numeric: 729,
    'English short name': 'Sudan (the)',
    'French short name': 'Soudan (le)',
    'Avarni name (Original)': 'sudan',
    'Avarni name (Updated)': 'Sudan',
    'Alternate Spellings':
      'Republic of Sudan, The Republic of the Sudan, The Sudan',
  },
  {
    'Alpha-2 code': 'SR',
    'Alpha-3 code': 'SUR',
    Numeric: 740,
    'English short name': 'Suriname',
    'French short name': 'Suriname (le)',
    'Avarni name (Original)': 'suriname',
    'Avarni name (Updated)': 'Suriname',
    'Alternate Spellings': 'Republic of Suriname',
  },
  {
    'Alpha-2 code': 'SJ',
    'Alpha-3 code': 'SJM',
    Numeric: 744,
    'English short name': 'Svalbard and Jan Mayen',
    'French short name': "Svalbard et l'Île Jan Mayen (le)",
    'Avarni name (Original)': '',
    'Avarni name (Updated)': 'Svalbard And Jan Mayen',
    'Alternate Spellings': 'Svalbard & Jan Mayen, Svalbard, Jan Mayen',
  },
  {
    'Alpha-2 code': 'SE',
    'Alpha-3 code': 'SWE',
    Numeric: 752,
    'English short name': 'Sweden',
    'French short name': 'Suède (la)',
    'Avarni name (Original)': 'sweden',
    'Avarni name (Updated)': 'Sweden',
    'Alternate Spellings': 'Kingdom of Sweden',
  },
  {
    'Alpha-2 code': 'CH',
    'Alpha-3 code': 'CHE',
    Numeric: 756,
    'English short name': 'Switzerland',
    'French short name': 'Suisse (la)',
    'Avarni name (Original)': 'switzerland',
    'Avarni name (Updated)': 'Switzerland',
    'Alternate Spellings': 'Swiss Confederation',
  },
  {
    'Alpha-2 code': 'SY',
    'Alpha-3 code': 'SYR',
    Numeric: 760,
    'English short name': 'Syrian Arab Republic (the)',
    'French short name': 'République arabe syrienne (la)',
    'Avarni name (Original)': 'syria',
    'Avarni name (Updated)': 'Syria',
    'Alternate Spellings': 'The Syrian Arab Republic, Syrian Arab Republic',
  },
  {
    'Alpha-2 code': 'TW',
    'Alpha-3 code': 'TWN',
    Numeric: 158,
    'English short name': 'Taiwan (Province of China)',
    'French short name': 'Taïwan (Province de Chine)',
    'Avarni name (Original)': 'taiwan',
    'Avarni name (Updated)': 'Taiwan',
    'Alternate Spellings': '',
  },
  {
    'Alpha-2 code': 'TJ',
    'Alpha-3 code': 'TJK',
    Numeric: 762,
    'English short name': 'Tajikistan',
    'French short name': 'Tadjikistan (le)',
    'Avarni name (Original)': 'tajikistan',
    'Avarni name (Updated)': 'Tajikistan',
    'Alternate Spellings': 'Republic of Tajikistan',
  },
  {
    'Alpha-2 code': 'TZ',
    'Alpha-3 code': 'TZA',
    Numeric: 834,
    'English short name': 'Tanzania, the United Republic of',
    'French short name': 'Tanzanie (la République-Unie de)',
    'Avarni name (Original)': 'tanzania',
    'Avarni name (Updated)': 'Tanzania',
    'Alternate Spellings':
      'The United Republic of Tanzania, United Republic of Tanzania',
  },
  {
    'Alpha-2 code': 'TH',
    'Alpha-3 code': 'THA',
    Numeric: 764,
    'English short name': 'Thailand',
    'French short name': 'Thaïlande (la)',
    'Avarni name (Original)': 'thailand',
    'Avarni name (Updated)': 'Thailand',
    'Alternate Spellings': 'Kingdom of Thailand',
  },
  {
    'Alpha-2 code': 'TL',
    'Alpha-3 code': 'TLS',
    Numeric: 626,
    'English short name': 'Timor-Leste',
    'French short name': 'Timor-Leste (le)',
    'Avarni name (Original)': 'east timor',
    'Avarni name (Updated)': 'East Timor',
    'Alternate Spellings':
      'Democratic Republic of Timor-Leste, Timor-Leste, Timor Leste',
  },
  {
    'Alpha-2 code': 'TG',
    'Alpha-3 code': 'TGO',
    Numeric: 768,
    'English short name': 'Togo',
    'French short name': 'Togo (le)',
    'Avarni name (Original)': 'togo',
    'Avarni name (Updated)': 'Togo',
    'Alternate Spellings': 'Togolese Republic',
  },
  {
    'Alpha-2 code': 'TK',
    'Alpha-3 code': 'TKL',
    Numeric: 772,
    'English short name': 'Tokelau',
    'French short name': 'Tokelau (les)',
    'Avarni name (Original)': '',
    'Avarni name (Updated)': 'Tokelau',
    'Alternate Spellings': 'Tokelau Islands',
  },
  {
    'Alpha-2 code': 'TO',
    'Alpha-3 code': 'TON',
    Numeric: 776,
    'English short name': 'Tonga',
    'French short name': 'Tonga (les)',
    'Avarni name (Original)': 'tonga',
    'Avarni name (Updated)': 'Tonga',
    'Alternate Spellings': 'Kingdom of Tonga',
  },
  {
    'Alpha-2 code': 'TT',
    'Alpha-3 code': 'TTO',
    Numeric: 780,
    'English short name': 'Trinidad and Tobago',
    'French short name': 'Trinité-et-Tobago (la)',
    'Avarni name (Original)': 'trinidad & tobago',
    'Avarni name (Updated)': 'Trinidad & Tobago',
    'Alternate Spellings': 'Trinidad and Tobago',
  },
  {
    'Alpha-2 code': 'TN',
    'Alpha-3 code': 'TUN',
    Numeric: 788,
    'English short name': 'Tunisia',
    'French short name': 'Tunisie (la)',
    'Avarni name (Original)': 'tunisia',
    'Avarni name (Updated)': 'Tunisia',
    'Alternate Spellings': 'Tunisian Republic',
  },
  {
    'Alpha-2 code': 'TM',
    'Alpha-3 code': 'TKM',
    Numeric: 795,
    'English short name': 'Turkmenistan',
    'French short name': 'Turkménistan (le)',
    'Avarni name (Original)': 'turkmenistan',
    'Avarni name (Updated)': 'Turkmenistan',
    'Alternate Spellings': 'Republic of Turkmenistan',
  },
  {
    'Alpha-2 code': 'TC',
    'Alpha-3 code': 'TCA',
    Numeric: 796,
    'English short name': 'Turks and Caicos Islands (the)',
    'French short name': 'Turks-et-Caïcos (les Îles)',
    'Avarni name (Original)': '',
    'Avarni name (Updated)': 'Turks And Caicos Islands',
    'Alternate Spellings':
      'The Turks and Caicos Islands, Turks & Caicos Islands, The Turks & Caicos Islands',
  },
  {
    'Alpha-2 code': 'TV',
    'Alpha-3 code': 'TUV',
    Numeric: 798,
    'English short name': 'Tuvalu',
    'French short name': 'Tuvalu (les)',
    'Avarni name (Original)': 'tuvalu',
    'Avarni name (Updated)': 'Tuvalu',
    'Alternate Spellings': 'Tuvalu Islands',
  },
  {
    'Alpha-2 code': 'TR',
    'Alpha-3 code': 'TUR',
    Numeric: 792,
    'English short name': 'Türkiye',
    'French short name': 'Türkiye (la)',
    'Avarni name (Original)': 'turkey',
    'Avarni name (Updated)': 'Turkey',
    'Alternate Spellings': 'Republic of Turkey, Türkiye',
  },
  {
    'Alpha-2 code': 'UG',
    'Alpha-3 code': 'UGA',
    Numeric: 800,
    'English short name': 'Uganda',
    'French short name': "Ouganda (l')",
    'Avarni name (Original)': 'uganda',
    'Avarni name (Updated)': 'Uganda',
    'Alternate Spellings': 'Republic of Uganda',
  },
  {
    'Alpha-2 code': 'UA',
    'Alpha-3 code': 'UKR',
    Numeric: 804,
    'English short name': 'Ukraine',
    'French short name': "Ukraine (l')",
    'Avarni name (Original)': 'ukraine',
    'Avarni name (Updated)': 'Ukraine',
    'Alternate Spellings': '',
  },
  {
    'Alpha-2 code': 'AE',
    'Alpha-3 code': 'ARE',
    Numeric: 784,
    'English short name': 'United Arab Emirates (the)',
    'French short name': 'Émirats arabes unis (les)',
    'Avarni name (Original)': 'united arab emirates',
    'Avarni name (Updated)': 'United Arab Emirates',
    'Alternate Spellings':
      'The United Arab Emirates, United Arab Emirates, UAE, Emirates',
  },
  {
    'Alpha-2 code': 'GB',
    'Alpha-3 code': 'GBR',
    Numeric: 826,
    'English short name':
      'United Kingdom of Great Britain and Northern Ireland (the)',
    'French short name':
      "Royaume-Uni de Grande-Bretagne et d'Irlande du Nord (le)",
    'Avarni name (Original)': 'united kingdom',
    'Avarni name (Updated)': 'United Kingdom',
    'Alternate Spellings':
      'UK, England, Great Britain, Britain, Northern Ireland, The United Kingdom of Great Britain and Northern Ireland, United Kingdom of Great Britain and Northern Ireland',
  },
  {
    'Alpha-2 code': 'UM',
    'Alpha-3 code': 'UMI',
    Numeric: 581,
    'English short name': 'United States Minor Outlying Islands (the)',
    'French short name': 'Îles mineures éloignées des États-Unis (les)',
    'Avarni name (Original)': '',
    'Avarni name (Updated)': 'United States Minor Outlying Islands',
    'Alternate Spellings':
      'The United States Minor Outlying Islands, United States Minor Outlying Islands',
  },
  {
    'Alpha-2 code': 'US',
    'Alpha-3 code': 'USA',
    Numeric: 840,
    'English short name': 'United States of America (the)',
    'French short name': "États-Unis d'Amérique (les)",
    'Avarni name (Original)': 'united states',
    'Avarni name (Updated)': 'United States',
    'Alternate Spellings':
      'USA, US, United States of America, The United States of America',
  },
  {
    'Alpha-2 code': 'UY',
    'Alpha-3 code': 'URY',
    Numeric: 858,
    'English short name': 'Uruguay',
    'French short name': "Uruguay (l')",
    'Avarni name (Original)': 'uruguay',
    'Avarni name (Updated)': 'Uruguay',
    'Alternate Spellings': 'Oriental Republic of Uruguay',
  },
  {
    'Alpha-2 code': 'UZ',
    'Alpha-3 code': 'UZB',
    Numeric: 860,
    'English short name': 'Uzbekistan',
    'French short name': "Ouzbékistan (l')",
    'Avarni name (Original)': 'uzbekistan',
    'Avarni name (Updated)': 'Uzbekistan',
    'Alternate Spellings': 'Republic of Uzbekistan',
  },
  {
    'Alpha-2 code': 'VU',
    'Alpha-3 code': 'VUT',
    Numeric: 548,
    'English short name': 'Vanuatu',
    'French short name': 'Vanuatu (le)',
    'Avarni name (Original)': 'vanuatu',
    'Avarni name (Updated)': 'Vanuatu',
    'Alternate Spellings': 'Republic of Vanuatu',
  },
  {
    'Alpha-2 code': 'VE',
    'Alpha-3 code': 'VEN',
    Numeric: 862,
    'English short name': 'Venezuela (Bolivarian Republic of)',
    'French short name': 'Venezuela (République bolivarienne du)',
    'Avarni name (Original)': 'venezuela',
    'Avarni name (Updated)': 'Venezuela',
    'Alternate Spellings':
      'The Bolivarian Republic of Venezuela, Bolivarian Republic of Venezuela',
  },
  {
    'Alpha-2 code': 'VN',
    'Alpha-3 code': 'VNM',
    Numeric: 704,
    'English short name': 'Viet Nam',
    'French short name': 'Viet Nam (le)',
    'Avarni name (Original)': 'vietnam',
    'Avarni name (Updated)': 'Vietnam',
    'Alternate Spellings': 'Viet Nam, Socialist Republic of Vietnam',
  },
  {
    'Alpha-2 code': 'VG',
    'Alpha-3 code': 'VGB',
    Numeric: 92,
    'English short name': 'Virgin Islands (British)',
    'French short name': 'Vierges britanniques (les Îles)',
    'Avarni name (Original)': '',
    'Avarni name (Updated)': 'British Virgin Islands',
    'Alternate Spellings': 'Virgin Islands',
  },
  {
    'Alpha-2 code': 'VI',
    'Alpha-3 code': 'VIR',
    Numeric: 850,
    'English short name': 'Virgin Islands (U.S.)',
    'French short name': 'Vierges des États-Unis (les Îles)',
    'Avarni name (Original)': '',
    'Avarni name (Updated)': 'United States Virgin Islands',
    'Alternate Spellings':
      'United States Virgin Islands, USVI, US Virgin Islands, U.S. Virgin Islands, Virgin Islands of the United States',
  },
  {
    'Alpha-2 code': 'WF',
    'Alpha-3 code': 'WLF',
    Numeric: 876,
    'English short name': 'Wallis and Futuna',
    'French short name': 'Wallis-et-Futuna',
    'Avarni name (Original)': '',
    'Avarni name (Updated)': 'Wallis And Futuna',
    'Alternate Spellings':
      'Territory of the Wallis and Futuna, Wallis & Futuna, Territory of the Wallis & Futuna',
  },
  {
    'Alpha-2 code': 'EH',
    'Alpha-3 code': 'ESH',
    Numeric: 732,
    'English short name': 'Western Sahara*',
    'French short name': 'Sahara occidental (le)*',
    'Avarni name (Original)': '',
    'Avarni name (Updated)': 'Western Sahara',
    'Alternate Spellings': 'Western Sahara, Sahrawi Arab Democratic Republic',
  },
  {
    'Alpha-2 code': 'YE',
    'Alpha-3 code': 'YEM',
    Numeric: 887,
    'English short name': 'Yemen',
    'French short name': 'Yémen (le)',
    'Avarni name (Original)': 'yemen',
    'Avarni name (Updated)': 'Yemen',
    'Alternate Spellings': 'Republic of Yemen',
  },
  {
    'Alpha-2 code': 'ZM',
    'Alpha-3 code': 'ZMB',
    Numeric: 894,
    'English short name': 'Zambia',
    'French short name': 'Zambie (la)',
    'Avarni name (Original)': 'zambia',
    'Avarni name (Updated)': 'Zambia',
    'Alternate Spellings': 'Republic of Zambia',
  },
  {
    'Alpha-2 code': 'ZW',
    'Alpha-3 code': 'ZWE',
    Numeric: 716,
    'English short name': 'Zimbabwe',
    'French short name': 'Zimbabwe (le)',
    'Avarni name (Original)': 'zimbabwe',
    'Avarni name (Updated)': 'Zimbabwe',
    'Alternate Spellings': 'Republic of Zimbabwe',
  },
  {
    'Alpha-2 code': 'AX',
    'Alpha-3 code': 'ALA',
    Numeric: 248,
    'English short name': 'Åland Islands',
    'French short name': 'Åland(les Îles)',
    'Avarni name (Original)': '',
    'Avarni name (Updated)': 'Åland Islands',
    'Alternate Spellings': 'Åland',
  },
];

fs.writeFileSync(
  'countries.json',
  JSON.stringify(
    countriesJSON.map((country) => {
      return {
        alpha2Code: country['Alpha-2 code'].toLowerCase(),
        alpha3Code: country['Alpha-3 code'].toLowerCase(),
        name: country['Avarni name (Original)'].toLowerCase() || country['Avarni name (Updated)']?.toLowerCase() || '',
        alternateNames: country['Alternate Spellings'].split(', ').filter((alternateName) => {
          return !!alternateName;
        }).map((alternateName) => alternateName.toLowerCase()),
      };
    }),
    null,
    2
  )
);
